name: ed-pooling
channels:
  - pytorch
  - defaults
dependencies:
  - flake8==3.7.9
  - python==3.6.9
  - pandas==1.1.2
  - pip==20.1.1
  - pytorch==1.6.0
  - psutil==5.7.2
  - spacy==2.3.2
  - nltk==3.4.5
  - torchvision==0.7.0
  - cudatoolkit==10.2.89
  - pip:
    - transformers==3.5.1
    - tensorboard==2.3.0
    - typing==3.7.4.3
    - pytorch-crf==0.7.2
    - seqeval==1.2.2
    - PyYAML==5.1.2
